spring:
    datasource:
        username: aiden
        password: qlqjs123
        url: jdbc:log4jdbc:mariadb://localhost:3306/kotlin_test
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                default_batch_fetch_size: 500
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        open-in-view: false

    profiles:
        include: oauth

    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: bdbeecc69f6d121012ea8055700e7cec
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: POST
                        client-name: Kakao
                        scope:
                            - profile_nickname
                            - account_email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id